version: 2
jobs:
  build:
    working_directory: ~/NightPharmacy
    docker:
      - image: circleci/ruby:2.4.1-node
        env:
          - PG_HOST=localhost
          - PG_USER=ubuntu
          - RAILS_ENV=test
          - RACK_ENV=test
      - image: circleci/postgres:9.6.3
        env:
          - POSTGRES_USER=ubuntu
          - POSTGRES_DB=night-pharmacy_test
    steps:
      - checkout
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run:
          name: Set up DB
          environment:
            DATABASE_URL: "postgres://ubuntu@localhost:5432/night-pharmacy_test"
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
      - run:
          name: Run tests
          command: bundle exec rake test
