version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node
        env:
          - RAILS_ENV=test
          - RACK_ENV=test
          - PG_HOST=localhost
          - PG_USER=ubuntu
          - DATABASE_URL=postgres://ubuntu@localhost:5432/night-pharmacy_test
      - image: circleci/postgres:9.6.3
        env:
          - POSTGRES_USER=ubuntu
          - POSTGRES_DB=night-pharmacy_test
    steps:
      - checkout
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run:
          name: Set up DB
          command: |
            bundle exec rake db:schema:load --trace
            bundle exec rake db:migrate
      - run:
          name: Run tests
          command: bundle exec rake test
